### ISSUE TITLE
DocDB simple queries with LLM

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind_data_outreach#26]
LLM tool to facilitate simple queries of the DocDB - where the MongoDB queries are pretty easy but still require users to know the syntax.

- [ ] Find assets with subject_id X
- [ ] Find assets of X modality, 
- [ ] Find assets of X project

**Comment by saskiad** [comment]
@dbirman add some other example queries that we can implement

**Comment by dbirman** [comment]
I think chained examples are where the LLM will really shine, because these ones are a pain to write like "I'm looking at asset name: ..., get me other assets that came from the same mouse with the same data modalities"

Or anything that does logic: "I need all assets from ecephys modality where the target coordinates are between X and Y on AP, and W and Z on ML". Another example: "Find all mice that were injected with virus X before date Y"
